version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1

jobs:
  build_docs:
    executor:
      name: python/default
      tag: '3.10'
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build/html
          paths: .
      - store_artifacts:
          path: docs/_build/html/

workflows:
  main:
    jobs:
      - build_docs
